version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
dockers:
  - image_templates: ["ghcr.io/shaharia-lab/echoy:{{ .Version }}"]
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/shaharia-lab/echoy
      - --label=org.opencontainers.image.source=https://github.com/shaharia-lab/echoy
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
nfpms:
  - id: echoy
    package_name: echoy
    vendor: shaharia-lab
    homepage: https://github.com/shaharia-lab/echoy
    maintainer: Shaharia Lab <hello@shaharialab.com>
    description: Echoy - intelligent & smart AI assistance for your daily life
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/echoy/copyright
    recommends:
      - git
