// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockFrontendDownloader is an autogenerated mock type for the FrontendDownloader type
type MockFrontendDownloader struct {
	mock.Mock
}

type MockFrontendDownloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFrontendDownloader) EXPECT() *MockFrontendDownloader_Expecter {
	return &MockFrontendDownloader_Expecter{mock: &_m.Mock}
}

// DownloadFrontend provides a mock function with no fields
func (_m *MockFrontendDownloader) DownloadFrontend() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DownloadFrontend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFrontendDownloader_DownloadFrontend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFrontend'
type MockFrontendDownloader_DownloadFrontend_Call struct {
	*mock.Call
}

// DownloadFrontend is a helper method to define mock.On call
func (_e *MockFrontendDownloader_Expecter) DownloadFrontend() *MockFrontendDownloader_DownloadFrontend_Call {
	return &MockFrontendDownloader_DownloadFrontend_Call{Call: _e.mock.On("DownloadFrontend")}
}

func (_c *MockFrontendDownloader_DownloadFrontend_Call) Run(run func()) *MockFrontendDownloader_DownloadFrontend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrontendDownloader_DownloadFrontend_Call) Return(_a0 error) *MockFrontendDownloader_DownloadFrontend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFrontendDownloader_DownloadFrontend_Call) RunAndReturn(run func() error) *MockFrontendDownloader_DownloadFrontend_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFrontendDownloader creates a new instance of MockFrontendDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFrontendDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFrontendDownloader {
	mock := &MockFrontendDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
