// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandFunc is an autogenerated mock type for the CommandFunc type
type MockCommandFunc struct {
	mock.Mock
}

type MockCommandFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandFunc) EXPECT() *MockCommandFunc_Expecter {
	return &MockCommandFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, args
func (_m *MockCommandFunc) Execute(ctx context.Context, args []string) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommandFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - args []string
func (_e *MockCommandFunc_Expecter) Execute(ctx interface{}, args interface{}) *MockCommandFunc_Execute_Call {
	return &MockCommandFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, args)}
}

func (_c *MockCommandFunc_Execute_Call) Run(run func(ctx context.Context, args []string)) *MockCommandFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockCommandFunc_Execute_Call) Return(response string, err error) *MockCommandFunc_Execute_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockCommandFunc_Execute_Call) RunAndReturn(run func(context.Context, []string) (string, error)) *MockCommandFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandFunc creates a new instance of MockCommandFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandFunc {
	mock := &MockCommandFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
