// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStylePrinter is an autogenerated mock type for the StylePrinter type
type MockStylePrinter struct {
	mock.Mock
}

type MockStylePrinter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStylePrinter) EXPECT() *MockStylePrinter_Expecter {
	return &MockStylePrinter_Expecter{mock: &_m.Mock}
}

// Print provides a mock function with given fields: a
func (_m *MockStylePrinter) Print(a ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, a...)
	_m.Called(_ca...)
}

// MockStylePrinter_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type MockStylePrinter_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
//   - a ...interface{}
func (_e *MockStylePrinter_Expecter) Print(a ...interface{}) *MockStylePrinter_Print_Call {
	return &MockStylePrinter_Print_Call{Call: _e.mock.On("Print",
		append([]interface{}{}, a...)...)}
}

func (_c *MockStylePrinter_Print_Call) Run(run func(a ...interface{})) *MockStylePrinter_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockStylePrinter_Print_Call) Return() *MockStylePrinter_Print_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStylePrinter_Print_Call) RunAndReturn(run func(...interface{})) *MockStylePrinter_Print_Call {
	_c.Run(run)
	return _c
}

// Printf provides a mock function with given fields: format, a
func (_m *MockStylePrinter) Printf(format string, a ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, a...)
	_m.Called(_ca...)
}

// MockStylePrinter_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type MockStylePrinter_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - format string
//   - a ...interface{}
func (_e *MockStylePrinter_Expecter) Printf(format interface{}, a ...interface{}) *MockStylePrinter_Printf_Call {
	return &MockStylePrinter_Printf_Call{Call: _e.mock.On("Printf",
		append([]interface{}{format}, a...)...)}
}

func (_c *MockStylePrinter_Printf_Call) Run(run func(format string, a ...interface{})) *MockStylePrinter_Printf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockStylePrinter_Printf_Call) Return() *MockStylePrinter_Printf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStylePrinter_Printf_Call) RunAndReturn(run func(string, ...interface{})) *MockStylePrinter_Printf_Call {
	_c.Run(run)
	return _c
}

// Println provides a mock function with given fields: a
func (_m *MockStylePrinter) Println(a ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, a...)
	_m.Called(_ca...)
}

// MockStylePrinter_Println_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Println'
type MockStylePrinter_Println_Call struct {
	*mock.Call
}

// Println is a helper method to define mock.On call
//   - a ...interface{}
func (_e *MockStylePrinter_Expecter) Println(a ...interface{}) *MockStylePrinter_Println_Call {
	return &MockStylePrinter_Println_Call{Call: _e.mock.On("Println",
		append([]interface{}{}, a...)...)}
}

func (_c *MockStylePrinter_Println_Call) Run(run func(a ...interface{})) *MockStylePrinter_Println_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockStylePrinter_Println_Call) Return() *MockStylePrinter_Println_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStylePrinter_Println_Call) RunAndReturn(run func(...interface{})) *MockStylePrinter_Println_Call {
	_c.Run(run)
	return _c
}

// NewMockStylePrinter creates a new instance of MockStylePrinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStylePrinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStylePrinter {
	mock := &MockStylePrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
