name: Pull Request Auto-Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [ "main", "feature/**" ]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Run PR Labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true